fix field last-name and body lock to form-participant
VinITAAcademy/dobrogo_vechora_dark2 pull request #52
Opened 2023-09-28 17:39 UTC by Belimoru

2023-09-28 17:46 UTC, OleksandrZhelihovskyi reviewed
use let instead of var

2023-09-28 19:55 UTC, VitaliyBogdanuk commented
conflict @Belimoru @OleksandrZhelihovskyi

2023-09-28 21:36 UTC, VitaliyBogdanuk requested changes

2023-09-29 06:21 UTC, Belimoru commented on src/js/script.js
> +    document.getElementById("last-name-partner").addEventListener("input", function() {
Remowed

2023-09-29 10:41 UTC, merged