Task/dv 4 block 3 about program
VinITAAcademy/dobrogo_vechora_dark2 pull request #7
Opened 2023-09-16 20:03 UTC by KatyaGanchuk

2023-09-16 22:25 UTC, OleksandrZhelihovskyi approved these changes

2023-09-17 16:02 UTC, VitaliyBogdanuk requested changes

2023-09-17 16:02 UTC, VitaliyBogdanuk commented on index.html
> +    <div class="container my-container">
що це за назва класа my-container? А чого не контейнер Васі чи Петі?

2023-09-17 16:02 UTC, VitaliyBogdanuk commented on index.html
> +
перевірти чи всі теги ви позакривали

2023-09-17 16:18 UTC, KatyaGanchuk commented on index.html
> +    <div class="container my-container">
Все виправлю

2023-09-17 16:39 UTC, KatyaGanchuk commented on index.html
> +
Перевірила,виправила

2023-09-18 08:23 UTC, merged