created list specialisation with button registration
VinITAAcademy/dobrogo_vechora_dark2 pull request #8
Opened 2023-09-17 12:57 UTC by C17H21NO4-AND

2023-09-17 16:05 UTC, VitaliyBogdanuk requested changes

2023-09-17 16:05 UTC, VitaliyBogdanuk commented on index.html
> +    <header class="header" id="test">
видаліть тестову id

2023-09-17 16:05 UTC, VitaliyBogdanuk commented on index.html
> +    <div class="conteiner-for-list-study conteiner">
цей код не можливо читати, зробіть вирівнювання

2023-09-17 16:05 UTC, VitaliyBogdanuk commented on src/css/style.css
> +#test .header-body select option {
тут теж видаліть тестову id

2023-09-17 16:37 UTC, C17H21NO4-AND commented on index.html
> +    <header class="header" id="test">
Виконав

2023-09-17 16:39 UTC, C17H21NO4-AND commented on index.html
> +    <div class="conteiner-for-list-study conteiner">
Виконав ,проставив в ручну табуляцію ,тільки в гітові код показуєтся, після змін не вірно в vs коді все виглядає гарно ,також не знаю чи правильно вигрузив зміни , як виправив код, зробив git push.

2023-09-18 08:27 UTC, VitaliyBogdanuk commented
Використовуйте VS code для форматування коду, як це зробити можна прочитати тут https://www.alphr.com/auto-format-vs-code/

Також пропишіть стилі так як ми з вами говорили, викоритовуючи ID та ланцюжки для ізоляції.

2023-09-18 10:00 UTC, OleksandrZhelihovskyi reviewed
Кольори потрібно задавати в форматі var() замість номеру кольору. Якщо в руті кольору немає - створюєте нову змінну.
Також зверніть увагу куди ви робите ПР

2023-09-19 17:45 UTC, VitaliyBogdanuk requested changes

2023-09-19 17:45 UTC, VitaliyBogdanuk commented on index.html
> +                    <p class="text-for-start-point-mid"> - Програмістом <br>
Зробіть це через список
```
<ul>
  <li></li>
</ul>
```

2023-09-19 17:46 UTC, OleksandrZhelihovskyi approved these changes

2023-09-19 20:17 UTC, merged